export const apiVersion = "v1";

export const routes = {
  health: "/api/v1/health",
  session: "/api/v1/auth/session",
  register: "/api/v1/auth/register",
  login: "/api/v1/auth/login",
  logout: "/api/v1/auth/logout",
  passwordResetRequest: "/api/v1/auth/password-reset/request",
  passwordResetConfirm: "/api/v1/auth/password-reset/confirm",
  passwordChange: "/api/v1/auth/password/change",
  mfaStatus: "/api/v1/auth/mfa",
  mfaTotpEnroll: "/api/v1/auth/mfa/totp/enroll",
  mfaTotpConfirm: "/api/v1/auth/mfa/totp/confirm",
  mfaTotpDisable: "/api/v1/auth/mfa/totp",
  authSessions: "/api/v1/auth/sessions",
  authSession: (sessionId: string) => `/api/v1/auth/sessions/${sessionId}`,
  oidcConfig: "/api/v1/auth/oidc/config",
  oidcStart: "/api/v1/auth/oidc/start",
  oidcCallback: "/api/v1/auth/oidc/callback",
  adminUsers: "/api/v1/admin/users",
  adminUser: (userId: string) => `/api/v1/admin/users/${userId}`,
  adminUserPasswordReset: (userId: string) => `/api/v1/admin/users/${userId}/password-reset`,
  adminUserSessions: (userId: string) => `/api/v1/admin/users/${userId}/sessions`,
  adminSessions: "/api/v1/admin/sessions",
  adminSession: (sessionId: string) => `/api/v1/admin/sessions/${sessionId}`,
  adminEmailOutbox: "/api/v1/admin/email-outbox",
  adminScimGroupRoleMappings: "/api/v1/admin/scim/group-role-mappings",
  adminScimGroupRoleMapping: (mappingId: string) => `/api/v1/admin/scim/group-role-mappings/${mappingId}`,
  scimServiceProviderConfig: "/api/v1/scim/v2/ServiceProviderConfig",
  scimUsers: "/api/v1/scim/v2/Users",
  scimUser: (userId: string) => `/api/v1/scim/v2/Users/${userId}`,
  scimGroups: "/api/v1/scim/v2/Groups",
  scimGroup: (groupId: string) => `/api/v1/scim/v2/Groups/${groupId}`,
  adminAssetStorage: "/api/v1/admin/assets/storage",
  adminAssetMigration: "/api/v1/admin/assets/migrate",
  adminAssetCleanup: "/api/v1/admin/assets/cleanup",
  campaigns: "/api/v1/campaigns",
  campaign: (campaignId: string) => `/api/v1/campaigns/${campaignId}`,
  campaignInvites: (campaignId: string) => `/api/v1/campaigns/${campaignId}/invites`,
  acceptInvite: "/api/v1/invites/accept",
  revokeInvite: (inviteId: string) => `/api/v1/invites/${inviteId}/revoke`,
  scenes: (campaignId: string) => `/api/v1/campaigns/${campaignId}/scenes`,
  assets: (campaignId: string) => `/api/v1/campaigns/${campaignId}/assets`,
  assetStorage: (campaignId: string) => `/api/v1/campaigns/${campaignId}/assets/storage`,
  uploadAsset: (campaignId: string) => `/api/v1/campaigns/${campaignId}/assets/upload`,
  assetBlob: (assetId: string) => `/api/v1/assets/${assetId}/blob`,
  assetDeliveryUrl: (assetId: string) => `/api/v1/assets/${assetId}/delivery-url`,
  assetLifecycle: (assetId: string) => `/api/v1/assets/${assetId}/lifecycle`,
  scene: (sceneId: string) => `/api/v1/scenes/${sceneId}`,
  sceneVision: (sceneId: string) => `/api/v1/scenes/${sceneId}/vision`,
  sceneFog: (sceneId: string) => `/api/v1/scenes/${sceneId}/fog`,
  sceneFogRegion: (sceneId: string, fogId: string) => `/api/v1/scenes/${sceneId}/fog/${fogId}`,
  sceneWalls: (sceneId: string) => `/api/v1/scenes/${sceneId}/walls`,
  sceneLights: (sceneId: string) => `/api/v1/scenes/${sceneId}/lights`,
  tokens: (sceneId: string) => `/api/v1/scenes/${sceneId}/tokens`,
  token: (tokenId: string) => `/api/v1/tokens/${tokenId}`,
  actors: (campaignId: string) => `/api/v1/campaigns/${campaignId}/actors`,
  actor: (actorId: string) => `/api/v1/actors/${actorId}`,
  items: (campaignId: string) => `/api/v1/campaigns/${campaignId}/items`,
  journals: (campaignId: string) => `/api/v1/campaigns/${campaignId}/journal`,
  journal: (entryId: string) => `/api/v1/journal/${entryId}`,
  chat: "/api/v1/chat/messages",
  dice: "/api/v1/dice/roll",
  encounters: (campaignId: string) => `/api/v1/campaigns/${campaignId}/encounters`,
  combats: (campaignId: string) => `/api/v1/campaigns/${campaignId}/combats`,
  proposals: (campaignId: string) => `/api/v1/campaigns/${campaignId}/proposals`,
  proposal: (proposalId: string) => `/api/v1/proposals/${proposalId}`,
  aiThreads: (campaignId: string) => `/api/v1/campaigns/${campaignId}/ai/threads`,
  aiUsage: (campaignId: string) => `/api/v1/campaigns/${campaignId}/ai/usage`,
  aiMemory: (campaignId: string) => `/api/v1/campaigns/${campaignId}/ai/memory`,
  aiMemoryExtract: (campaignId: string) => `/api/v1/campaigns/${campaignId}/ai/memory/extract`,
  aiToolCalls: (campaignId: string) => `/api/v1/campaigns/${campaignId}/ai/tool-calls`,
  aiSessionRecap: (campaignId: string) => `/api/v1/campaigns/${campaignId}/ai/session-recap`,
  aiEncounterDesign: (campaignId: string) => `/api/v1/campaigns/${campaignId}/ai/encounter-design`,
  systems: "/api/v1/systems",
  campaignSystems: (campaignId: string) => `/api/v1/campaigns/${campaignId}/systems`,
  campaignSystem: (campaignId: string, systemId: string) => `/api/v1/campaigns/${campaignId}/systems/${systemId}`,
  systemCharacterTemplates: (campaignId: string, systemId: string) => `/api/v1/campaigns/${campaignId}/systems/${systemId}/character-templates`,
  systemCharacters: (campaignId: string, systemId: string) => `/api/v1/campaigns/${campaignId}/systems/${systemId}/characters`,
  systemCharacterImport: (campaignId: string, systemId: string) => `/api/v1/campaigns/${campaignId}/systems/${systemId}/characters/import`,
  systemEncounterThreats: (campaignId: string, systemId: string) => `/api/v1/campaigns/${campaignId}/systems/${systemId}/encounter-threats`,
  systemEncounterPlan: (campaignId: string, systemId: string) => `/api/v1/campaigns/${campaignId}/systems/${systemId}/encounter-plan`,
  systemCompendium: (campaignId: string, systemId: string) => `/api/v1/campaigns/${campaignId}/systems/${systemId}/compendium`,
  systemActorCompendium: (campaignId: string, systemId: string, actorId: string) => `/api/v1/campaigns/${campaignId}/systems/${systemId}/actors/${actorId}/compendium`,
  systemActorConditions: (campaignId: string, systemId: string, actorId: string) => `/api/v1/campaigns/${campaignId}/systems/${systemId}/actors/${actorId}/conditions`,
  systemActorCondition: (campaignId: string, systemId: string, actorId: string, conditionId: string) => `/api/v1/campaigns/${campaignId}/systems/${systemId}/actors/${actorId}/conditions/${conditionId}`,
  systemActorAdvancement: (campaignId: string, systemId: string, actorId: string) => `/api/v1/campaigns/${campaignId}/systems/${systemId}/actors/${actorId}/advancement`,
  systemActorAdvance: (campaignId: string, systemId: string, actorId: string) => `/api/v1/campaigns/${campaignId}/systems/${systemId}/actors/${actorId}/advance`,
  systemActorSheet: (campaignId: string, systemId: string, actorId: string) => `/api/v1/campaigns/${campaignId}/systems/${systemId}/actors/${actorId}/sheet`,
  systemActorRoll: (campaignId: string, systemId: string, actorId: string) => `/api/v1/campaigns/${campaignId}/systems/${systemId}/actors/${actorId}/roll`,
  plugins: "/api/v1/plugins",
  pluginRegistrySync: "/api/v1/plugins/registry/sync",
  campaignPlugins: (campaignId: string) => `/api/v1/campaigns/${campaignId}/plugins`,
  campaignPlugin: (campaignId: string, pluginId: string) => `/api/v1/campaigns/${campaignId}/plugins/${pluginId}`,
  pluginChatCommand: (campaignId: string, pluginId: string) => `/api/v1/campaigns/${campaignId}/plugins/${pluginId}/chat-command`,
  exportCampaign: (campaignId: string) => `/api/v1/campaigns/${campaignId}/export`,
  importCampaign: "/api/v1/import/campaign"
} as const;

const endpointSpecs = [
  ["GET", routes.health],
  ["POST", routes.register],
  ["POST", routes.login],
  ["POST", routes.logout],
  ["POST", routes.passwordResetRequest],
  ["POST", routes.passwordResetConfirm],
  ["POST", routes.passwordChange],
  ["GET", routes.mfaStatus],
  ["POST", routes.mfaTotpEnroll],
  ["POST", routes.mfaTotpConfirm],
  ["DELETE", routes.mfaTotpDisable],
  ["GET", routes.session],
  ["GET", routes.authSessions],
  ["DELETE", "/api/v1/auth/sessions/{sessionId}"],
  ["GET", routes.oidcConfig],
  ["GET", routes.oidcStart],
  ["POST", routes.oidcStart],
  ["GET", routes.oidcCallback],
  ["GET", routes.adminUsers],
  ["PATCH", "/api/v1/admin/users/{userId}"],
  ["POST", "/api/v1/admin/users/{userId}/password-reset"],
  ["DELETE", "/api/v1/admin/users/{userId}/sessions"],
  ["GET", routes.adminSessions],
  ["DELETE", "/api/v1/admin/sessions/{sessionId}"],
  ["GET", routes.adminEmailOutbox],
  ["GET", routes.adminScimGroupRoleMappings],
  ["POST", routes.adminScimGroupRoleMappings],
  ["DELETE", "/api/v1/admin/scim/group-role-mappings/{mappingId}"],
  ["GET", routes.scimServiceProviderConfig],
  ["GET", routes.scimUsers],
  ["POST", routes.scimUsers],
  ["GET", "/api/v1/scim/v2/Users/{userId}"],
  ["PUT", "/api/v1/scim/v2/Users/{userId}"],
  ["PATCH", "/api/v1/scim/v2/Users/{userId}"],
  ["DELETE", "/api/v1/scim/v2/Users/{userId}"],
  ["GET", routes.scimGroups],
  ["POST", routes.scimGroups],
  ["GET", "/api/v1/scim/v2/Groups/{groupId}"],
  ["PUT", "/api/v1/scim/v2/Groups/{groupId}"],
  ["PATCH", "/api/v1/scim/v2/Groups/{groupId}"],
  ["DELETE", "/api/v1/scim/v2/Groups/{groupId}"],
  ["GET", routes.adminAssetStorage],
  ["POST", routes.adminAssetMigration],
  ["POST", routes.adminAssetCleanup],
  ["GET", routes.campaigns],
  ["POST", routes.campaigns],
  ["GET", "/api/v1/campaigns/{campaignId}"],
  ["PATCH", "/api/v1/campaigns/{campaignId}"],
  ["DELETE", "/api/v1/campaigns/{campaignId}"],
  ["GET", "/api/v1/campaigns/{campaignId}/invites"],
  ["POST", "/api/v1/campaigns/{campaignId}/invites"],
  ["POST", routes.acceptInvite],
  ["POST", "/api/v1/invites/{inviteId}/revoke"],
  ["GET", "/api/v1/campaigns/{campaignId}/scenes"],
  ["POST", "/api/v1/campaigns/{campaignId}/scenes"],
  ["GET", "/api/v1/campaigns/{campaignId}/assets"],
  ["GET", "/api/v1/campaigns/{campaignId}/assets/storage"],
  ["POST", "/api/v1/campaigns/{campaignId}/assets"],
  ["POST", "/api/v1/campaigns/{campaignId}/assets/upload"],
  ["GET", "/api/v1/assets/{assetId}/blob"],
  ["POST", "/api/v1/assets/{assetId}/delivery-url"],
  ["PATCH", "/api/v1/assets/{assetId}/lifecycle"],
  ["GET", "/api/v1/scenes/{sceneId}"],
  ["PATCH", "/api/v1/scenes/{sceneId}"],
  ["DELETE", "/api/v1/scenes/{sceneId}"],
  ["GET", "/api/v1/scenes/{sceneId}/vision"],
  ["POST", "/api/v1/scenes/{sceneId}/fog"],
  ["DELETE", "/api/v1/scenes/{sceneId}/fog/{fogId}"],
  ["POST", "/api/v1/scenes/{sceneId}/walls"],
  ["POST", "/api/v1/scenes/{sceneId}/lights"],
  ["GET", "/api/v1/scenes/{sceneId}/tokens"],
  ["POST", "/api/v1/scenes/{sceneId}/tokens"],
  ["PATCH", "/api/v1/tokens/{tokenId}"],
  ["DELETE", "/api/v1/tokens/{tokenId}"],
  ["GET", "/api/v1/campaigns/{campaignId}/actors"],
  ["POST", "/api/v1/campaigns/{campaignId}/actors"],
  ["GET", "/api/v1/campaigns/{campaignId}/journal"],
  ["POST", "/api/v1/campaigns/{campaignId}/journal"],
  ["POST", routes.dice],
  ["POST", routes.chat],
  ["GET", routes.chat],
  ["GET", "/api/v1/campaigns/{campaignId}/ai/threads"],
  ["POST", "/api/v1/campaigns/{campaignId}/ai/threads"],
  ["GET", "/api/v1/campaigns/{campaignId}/ai/usage"],
  ["POST", "/api/v1/campaigns/{campaignId}/ai/memory/extract"],
  ["GET", "/api/v1/campaigns/{campaignId}/ai/tool-calls"],
  ["GET", routes.plugins],
  ["POST", "/api/v1/plugins/install"],
  ["POST", routes.pluginRegistrySync],
  ["GET", "/api/v1/campaigns/{campaignId}/plugins"],
  ["POST", "/api/v1/campaigns/{campaignId}/plugins/{pluginId}/install"],
  ["POST", "/api/v1/campaigns/{campaignId}/plugins/{pluginId}/chat-command"],
  ["GET", routes.systems],
  ["POST", "/api/v1/systems/install"],
  ["GET", "/api/v1/campaigns/{campaignId}/systems"],
  ["POST", "/api/v1/campaigns/{campaignId}/systems/{systemId}/install"],
  ["GET", "/api/v1/campaigns/{campaignId}/systems/{systemId}/character-templates"],
  ["POST", "/api/v1/campaigns/{campaignId}/systems/{systemId}/characters"],
  ["POST", "/api/v1/campaigns/{campaignId}/systems/{systemId}/characters/import"],
  ["GET", "/api/v1/campaigns/{campaignId}/systems/{systemId}/encounter-threats"],
  ["POST", "/api/v1/campaigns/{campaignId}/systems/{systemId}/encounter-plan"],
  ["GET", "/api/v1/campaigns/{campaignId}/systems/{systemId}/compendium"],
  ["POST", "/api/v1/campaigns/{campaignId}/systems/{systemId}/actors/{actorId}/compendium"],
  ["POST", "/api/v1/campaigns/{campaignId}/systems/{systemId}/actors/{actorId}/conditions"],
  ["DELETE", "/api/v1/campaigns/{campaignId}/systems/{systemId}/actors/{actorId}/conditions/{conditionId}"],
  ["GET", "/api/v1/campaigns/{campaignId}/systems/{systemId}/actors/{actorId}/advancement"],
  ["POST", "/api/v1/campaigns/{campaignId}/systems/{systemId}/actors/{actorId}/advance"],
  ["GET", "/api/v1/campaigns/{campaignId}/systems/{systemId}/actors/{actorId}/sheet"],
  ["POST", "/api/v1/campaigns/{campaignId}/systems/{systemId}/actors/{actorId}/roll"]
] as const;

const okResponse = {
  responses: {
    "200": {
      description: "OK"
    }
  }
};

const paths = endpointSpecs.reduce<Record<string, Record<string, typeof okResponse>>>((items, [method, path]) => {
  items[path] ??= {};
  items[path][method.toLowerCase()] = okResponse;
  return items;
}, {});

export const openApiSpec = {
  openapi: "3.1.0",
  info: {
    title: "OpenTabletop Engine API",
    version: "0.1.0"
  },
  paths
};
